name: VSBuild Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: kirandevops1993/VS-BUILD-TASK-REUSABLE-/.github/workflows/vsbuildtask-reusable.yml@main
    with:
      logProjectEvents: true
      vsVersion: "latest"
      enableDefaultLogger: true
      restoreNugetArgs: "-NoCache"
      platform: "Any CPU"  
      configuration: "Release"
      maxCpu: 8
      clean: true
      vsbuildArguments: ""
      createLogFile: true
      logFileVerbosity: "detailed"
