
name: MAIN Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vstest-action:
    runs-on: "self-hosted"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: VS-TEST
        uses: ./.github/actions/VSTESTING
        with:
          runsOn: "self-hosted"
          dotnet-version: "9.0.203"
          testSelector: "testAssemblies"
          testAssemblyVer2: '*Abstractions.dll'
          code-coverage-enabled: true
          configuration: "Release"
          platform: "x64"
          test-run-title: "Unit Tests"
          run-in-parallel: true
          testPlan: "Plan1"
          testSuite: "SuiteA"
          testConfiguration: "DebugConfig"
          tcmTestRun: "1234"
          uiTests: false
          vsTestVersion: "latest"
          vstestLocation: "C:\\Program Files\\Microsoft Visual Studio\\2022\\community\\Common7\\IDE\\Extensions\\TestPlatform\\vstest.console.exe"
          runSettingsFile: "${{ github.workspace }}/TestSettings.runsettings"
          diagnosticsEnabled: true
          rerunFailedTests: true
          rerunType: "specific"
          rerunMaxAttempts: "3"
          dontDistribute: false
          searchFolder: "${{ github.workspace }}"
          resultsFolder: "$(Agent.TempDirectory)\\TestResults"
          testFiltercriteria: ""
          runOnlyImpactedTests: false
          runAllTestsAfterXBuilds: "50"
